### ISSUE TITLE
Consolidate github permissions

### ISSUE THREAD

**Issue by trickeydan** [roboticsoutreach/tasks#22]
The GitHub permissions need to be checked as @joe9599 was unable to write to camera-board-hw

**Comment by kierdavis** [comment]
The root cause was that camera-board-hw hadn't been added to the "Everyone" team. We should document that new repos need to be added to this team and/or investigate whether this can be automated.

In regard to the latter, we could set up a Github webhook to run a script [whenever a repository is created](https://developer.github.com/v3/activity/events/types/#repositoryevent), which could use Github's REST API to [add the repo to the team](https://developer.github.com/v3/teams/#add-or-update-team-repository).
