### ISSUE TITLE
Consider task management software

### ISSUE THREAD

**Issue by trickeydan** [roboticsoutreach/tasks#23]
GitHub is a bit intimidating to new volunteers.

We should see if we can find a better alternative

**Comment by trickeydan** [comment]
https://www.gitkraken.com/glo

**Comment by kierdavis** [comment]
Although I'm still of the opinion that "Github appears intimidating" is something that is better fixed by improving the quality and interactivity of our training rather than switching software, glo does seem pretty neat. I especially like the way it syncs with github issues; having more than one interface increases accessibility since different people prefer different interfaces.

We should also consider whether automation is available in whichever software we end up using. For example I think it would be both useful and reasonably simple to have a bot or script that gathers all the tasks in the previous summer school's milestones and re-creates them for next year.

**Comment by trickeydan** [comment]
> We should also consider whether automation is available in whichever software we end up using. For example I think it would be both useful and reasonably simple to have a bot or script that gathers all the tasks in the previous summer school's milestones and re-creates them for next year.

The API for GitHub is great. I'm planning to build a proper `sro-bot` that does a lot of things like mentioned #22, and messages events in slack etc. 

It will probably be nice and generic so that we can use it for SR though. Think like the countdown that @Tyler-Ward made.

**Comment by tpoomlmly** [comment]
GitHub has vastly improved its task management features in the last 4 years
